INSERT INTO tables_info (table_id, location, is_private, table_size) VALUES
(1, 'Terrace', FALSE, 4),
(2, 'Terrace', TRUE, 2),
(3, 'Inside', FALSE, 6),
(4, 'View of Sagrada Familia', TRUE, 4),
(5, 'Inside', FALSE, 8),
(6, 'Terrace', FALSE, 4),
(7, 'Terrace', TRUE, 2),
(8, 'Inside', FALSE, 6),
(9, 'View of Sagrada Familia', TRUE, 4),
(10, 'Inside', FALSE, 8),
(11, 'Terrace', FALSE, 4),
(12, 'Terrace', TRUE, 2),
(13, 'Inside', FALSE, 6),
(14, 'View of Sagrada Familia', TRUE, 4),
(15, 'Inside', FALSE, 8),
(16, 'Terrace', FALSE, 4),
(17, 'Terrace', TRUE, 2),
(18, 'Inside', FALSE, 6),
(19, 'View of Sagrada Familia', TRUE, 4),
(20, 'Inside', FALSE, 8);