INSERT INTO restaurant_metadata (table_name, column_name, description) VALUES
('restaurant_metadata', 'table_name', 'Name of the table in the database'),
('restaurant_metadata', 'column_name', 'Name of the column in the table'),
('restaurant_metadata', 'description', 'Description of current column'),
('restaurant_availability', 'table_id', 'Identifier for the table'),
('restaurant_availability', 'period', 'Time period for availability (e.g. 1_days_ahead, 2_days_ahead...)'),
('restaurant_availability', 'time_slot', "Specific time slot for the table. Possible values: '10:00-12:00', '12:00-14:00', '14:00-16:00', '16:00-18:00', '18:00-20:00' or '20:00-22:00'"),
('restaurant_availability', 'is_available', 'Availability status of the table'),
('restaurant_catalog', 'id', 'Unique identifier for each item'),
('restaurant_catalog', 'name', 'Name of the menu item'),
('restaurant_catalog', 'description', 'Description of the menu item'),
('restaurant_catalog', 'category', "Category of the menu item. Possible values: 'Appetizer', 'Salad', 'Main Course', 'Side', 'Dessert', 'Soup', 'Breakfast'"),
('restaurant_catalog', 'price', 'Price of the menu item'),
('restaurant_catalog', 'is_vegetarian', 'If menu items is vegetarian or not'),
('restaurant_catalog', 'is_gluten_free', 'If menu items is gluten free or not'),
('restaurant_catalog', 'is_spicy', 'If menu items is spicy or not'),
('restaurant_catalog', 'calories', 'Caloric content of the menu item'),
('tables_info', 'table_id', 'Unique identifier for each table'),
('tables_info', 'location', "Location of the table within the restaurant. Possible values: 'Terrace', 'Inside', 'View of Sagrada Familia'"),
('tables_info', 'is_private', 'If table is private or not'),
('tables_info', 'table_size', 'Size of the table in terms of seating capacity. Possible values: 4, 2, 6, 8');